/****************************************************************************
 * Description: 
 * 
 * Document: https://github.com/hiramtan/HiProtobuf
 * Author: hiramtan@live.com
 ****************************************************************************/

using System.Collections.Generic;
using System.IO;
using System.Linq;
using HiFramework.Assert;
using Microsoft.Office.Interop.Excel;

namespace HiProtobuf.Lib
{
    internal class ProtoGenerater
    {
        private string _name;

        private int _rowCount;

        private int _colCount;

        private Range _Range;

        private string _path;
        private int _index;
        public ProtoGenerater(string name, int rowCount, int colCount, Range range)
        {
            _name = name;
            _rowCount = rowCount;
            _colCount = colCount;
            _Range = range;

            _path = Settings.Export_Folder + Settings.proto_folder + "/" + name + ".proto";
        }

        public void Process()
        {
            ProcessHeader();
            ProcessVariables();
            ProcessMap();
        }

        void ProcessHeader()
        {
            var header = @"
// This is auto generated by HiProtobuf
// Support: hiramtan@live.com

// [START declaration]
syntax = ""proto3"";
package HiProtobuf;
// [END declaration]

// [START java_declaration]
option java_package = ""com.HiProtobuf.HiProtobuf"";
option java_outer_classname = ""{0}"";
// [END java_declaration]

// [START csharp_declaration]
option csharp_namespace = ""HiProtobuf""; 
// [END csharp_declaration]
";
            header = string.Format(header, _name + "_classname");
            var sw = File.AppendText(_path);
            sw.WriteLine(header);
            sw.Close();
        }

        void ProcessVariables()
        {
            var str = "message " + _name + " {\n";
            for (int j = 1; j <= _colCount; j++)
            {
                var type = ((Range)_Range.Cells[2, j]).Value2.ToString();
                var name = ((Range)_Range.Cells[3, j]).Value2.ToString();
                str += GetVariableString(type, name);
            }
            str += "}";
            var sw = File.AppendText(_path);
            sw.WriteLine(str);
            sw.Close();
        }

        /// <summary>
        /// 数组用[]标识
        /// </summary>
        /// <param name="infos"></param>
        private string GetVariableString(string type, string name)
        {
            AssertThat.IsTrue(Common.VariableType.Contains(type), "Type define error");

            _index++;//从1开始定义
            string str = "";
            if (type.Contains("[]"))//如果是数组进行转换
            {
                type = "repeated " + type.Split('[')[0];
            }
            str += "  " + type + " " + name + " = " + _index + ";";
            str += "\n";
            return str;
        }

        private void ProcessMap()
        {
            string str = @"
message Excel_{0}
{{
    map<int32,{1}> {2} = 1;
}}";
            str = string.Format(str, _name, _name, "Data");
            var sw = File.AppendText(_path);
            sw.WriteLine(str);
            sw.Close();
        }
    }
}
