name: discord message
on:
  issues:
    types: [opened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        username: "GitHub"
        message: ":loudspeaker: **${{github.event.issue.title}}**\n${{github.event.issue.html_url}}"
