// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package com.HiProtobuf.HiProtobuf;

public final class Test_classname {
  private Test_classname() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HiProtobuf.Test)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 hp = 3;</code>
     */
    int getHp();

    /**
     * <code>int32 attack = 4;</code>
     */
    int getAttack();

    /**
     * <code>repeated string infos = 5;</code>
     */
    java.util.List<java.lang.String>
        getInfosList();
    /**
     * <code>repeated string infos = 5;</code>
     */
    int getInfosCount();
    /**
     * <code>repeated string infos = 5;</code>
     */
    java.lang.String getInfos(int index);
    /**
     * <code>repeated string infos = 5;</code>
     */
    com.google.protobuf.ByteString
        getInfosBytes(int index);
  }
  /**
   * Protobuf type {@code HiProtobuf.Test}
   */
  public  static final class Test extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HiProtobuf.Test)
      TestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Test.newBuilder() to construct.
    private Test(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Test() {
      name_ = "";
      infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Test();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Test(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              hp_ = input.readInt32();
              break;
            }
            case 32: {

              attack_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                infos_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              infos_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          infos_ = infos_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Test_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Test_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.HiProtobuf.HiProtobuf.Test_classname.Test.class, com.HiProtobuf.HiProtobuf.Test_classname.Test.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HP_FIELD_NUMBER = 3;
    private int hp_;
    /**
     * <code>int32 hp = 3;</code>
     */
    public int getHp() {
      return hp_;
    }

    public static final int ATTACK_FIELD_NUMBER = 4;
    private int attack_;
    /**
     * <code>int32 attack = 4;</code>
     */
    public int getAttack() {
      return attack_;
    }

    public static final int INFOS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList infos_;
    /**
     * <code>repeated string infos = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInfosList() {
      return infos_;
    }
    /**
     * <code>repeated string infos = 5;</code>
     */
    public int getInfosCount() {
      return infos_.size();
    }
    /**
     * <code>repeated string infos = 5;</code>
     */
    public java.lang.String getInfos(int index) {
      return infos_.get(index);
    }
    /**
     * <code>repeated string infos = 5;</code>
     */
    public com.google.protobuf.ByteString
        getInfosBytes(int index) {
      return infos_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (hp_ != 0) {
        output.writeInt32(3, hp_);
      }
      if (attack_ != 0) {
        output.writeInt32(4, attack_);
      }
      for (int i = 0; i < infos_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, infos_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (hp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, hp_);
      }
      if (attack_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, attack_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < infos_.size(); i++) {
          dataSize += computeStringSizeNoTag(infos_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInfosList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.HiProtobuf.HiProtobuf.Test_classname.Test)) {
        return super.equals(obj);
      }
      com.HiProtobuf.HiProtobuf.Test_classname.Test other = (com.HiProtobuf.HiProtobuf.Test_classname.Test) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getHp()
          != other.getHp()) return false;
      if (getAttack()
          != other.getAttack()) return false;
      if (!getInfosList()
          .equals(other.getInfosList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + HP_FIELD_NUMBER;
      hash = (53 * hash) + getHp();
      hash = (37 * hash) + ATTACK_FIELD_NUMBER;
      hash = (53 * hash) + getAttack();
      if (getInfosCount() > 0) {
        hash = (37 * hash) + INFOS_FIELD_NUMBER;
        hash = (53 * hash) + getInfosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Test parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.HiProtobuf.HiProtobuf.Test_classname.Test prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HiProtobuf.Test}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HiProtobuf.Test)
        com.HiProtobuf.HiProtobuf.Test_classname.TestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Test_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Test_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.HiProtobuf.HiProtobuf.Test_classname.Test.class, com.HiProtobuf.HiProtobuf.Test_classname.Test.Builder.class);
      }

      // Construct using com.HiProtobuf.HiProtobuf.Test_classname.Test.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        hp_ = 0;

        attack_ = 0;

        infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Test_descriptor;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Test_classname.Test getDefaultInstanceForType() {
        return com.HiProtobuf.HiProtobuf.Test_classname.Test.getDefaultInstance();
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Test_classname.Test build() {
        com.HiProtobuf.HiProtobuf.Test_classname.Test result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Test_classname.Test buildPartial() {
        com.HiProtobuf.HiProtobuf.Test_classname.Test result = new com.HiProtobuf.HiProtobuf.Test_classname.Test(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        result.hp_ = hp_;
        result.attack_ = attack_;
        if (((bitField0_ & 0x00000001) != 0)) {
          infos_ = infos_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.infos_ = infos_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.HiProtobuf.HiProtobuf.Test_classname.Test) {
          return mergeFrom((com.HiProtobuf.HiProtobuf.Test_classname.Test)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.HiProtobuf.HiProtobuf.Test_classname.Test other) {
        if (other == com.HiProtobuf.HiProtobuf.Test_classname.Test.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getHp() != 0) {
          setHp(other.getHp());
        }
        if (other.getAttack() != 0) {
          setAttack(other.getAttack());
        }
        if (!other.infos_.isEmpty()) {
          if (infos_.isEmpty()) {
            infos_ = other.infos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInfosIsMutable();
            infos_.addAll(other.infos_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.HiProtobuf.HiProtobuf.Test_classname.Test parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.HiProtobuf.HiProtobuf.Test_classname.Test) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int hp_ ;
      /**
       * <code>int32 hp = 3;</code>
       */
      public int getHp() {
        return hp_;
      }
      /**
       * <code>int32 hp = 3;</code>
       */
      public Builder setHp(int value) {
        
        hp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 hp = 3;</code>
       */
      public Builder clearHp() {
        
        hp_ = 0;
        onChanged();
        return this;
      }

      private int attack_ ;
      /**
       * <code>int32 attack = 4;</code>
       */
      public int getAttack() {
        return attack_;
      }
      /**
       * <code>int32 attack = 4;</code>
       */
      public Builder setAttack(int value) {
        
        attack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 attack = 4;</code>
       */
      public Builder clearAttack() {
        
        attack_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInfosIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          infos_ = new com.google.protobuf.LazyStringArrayList(infos_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getInfosList() {
        return infos_.getUnmodifiableView();
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public int getInfosCount() {
        return infos_.size();
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public java.lang.String getInfos(int index) {
        return infos_.get(index);
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public com.google.protobuf.ByteString
          getInfosBytes(int index) {
        return infos_.getByteString(index);
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder setInfos(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInfosIsMutable();
        infos_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder addInfos(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInfosIsMutable();
        infos_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder addAllInfos(
          java.lang.Iterable<java.lang.String> values) {
        ensureInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, infos_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder clearInfos() {
        infos_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string infos = 5;</code>
       */
      public Builder addInfosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureInfosIsMutable();
        infos_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HiProtobuf.Test)
    }

    // @@protoc_insertion_point(class_scope:HiProtobuf.Test)
    private static final com.HiProtobuf.HiProtobuf.Test_classname.Test DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.HiProtobuf.HiProtobuf.Test_classname.Test();
    }

    public static com.HiProtobuf.HiProtobuf.Test_classname.Test getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Test>
        PARSER = new com.google.protobuf.AbstractParser<Test>() {
      @java.lang.Override
      public Test parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Test(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Test> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Test> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.HiProtobuf.HiProtobuf.Test_classname.Test getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Excel_TestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HiProtobuf.Excel_Test)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;int32, .HiProtobuf.Test&gt; Data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>map&lt;int32, .HiProtobuf.Test&gt; Data = 1;</code>
     */
    boolean containsData(
        int key);
    /**
     * Use {@link #getDataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test>
    getData();
    /**
     * <code>map&lt;int32, .HiProtobuf.Test&gt; Data = 1;</code>
     */
    java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test>
    getDataMap();
    /**
     * <code>map&lt;int32, .HiProtobuf.Test&gt; Data = 1;</code>
     */

    com.HiProtobuf.HiProtobuf.Test_classname.Test getDataOrDefault(
        int key,
        com.HiProtobuf.HiProtobuf.Test_classname.Test defaultValue);
    /**
     * <code>map&lt;int32, .HiProtobuf.Test&gt; Data = 1;</code>
     */

    com.HiProtobuf.HiProtobuf.Test_classname.Test getDataOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code HiProtobuf.Excel_Test}
   */
  public  static final class Excel_Test extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HiProtobuf.Excel_Test)
      Excel_TestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Excel_Test.newBuilder() to construct.
    private Excel_Test(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Excel_Test() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Excel_Test();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Excel_Test(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                data_ = com.google.protobuf.MapField.newMapField(
                    DataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test>
              data__ = input.readMessage(
                  DataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              data_.getMutableMap().put(
                  data__.getKey(), data__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Excel_Test_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Excel_Test_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test.class, com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private static final class DataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test>newDefaultInstance(
                  com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Excel_Test_DataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.HiProtobuf.HiProtobuf.Test_classname.Test.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test> data_;
    private com.google.protobuf.MapField<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test>
    internalGetData() {
      if (data_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DataDefaultEntryHolder.defaultEntry);
      }
      return data_;
    }

    public int getDataCount() {
      return internalGetData().getMap().size();
    }
    /**
     * <code>map&lt;int32, .HiProtobuf.Test&gt; Data = 1;</code>
     */

    public boolean containsData(
        int key) {
      
      return internalGetData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDataMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test> getData() {
      return getDataMap();
    }
    /**
     * <code>map&lt;int32, .HiProtobuf.Test&gt; Data = 1;</code>
     */

    public java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test> getDataMap() {
      return internalGetData().getMap();
    }
    /**
     * <code>map&lt;int32, .HiProtobuf.Test&gt; Data = 1;</code>
     */

    public com.HiProtobuf.HiProtobuf.Test_classname.Test getDataOrDefault(
        int key,
        com.HiProtobuf.HiProtobuf.Test_classname.Test defaultValue) {
      
      java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test> map =
          internalGetData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .HiProtobuf.Test&gt; Data = 1;</code>
     */

    public com.HiProtobuf.HiProtobuf.Test_classname.Test getDataOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test> map =
          internalGetData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetData(),
          DataDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test> entry
           : internalGetData().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test>
        data__ = DataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, data__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test)) {
        return super.equals(obj);
      }
      com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test other = (com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test) obj;

      if (!internalGetData().equals(
          other.internalGetData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetData().getMap().isEmpty()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HiProtobuf.Excel_Test}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HiProtobuf.Excel_Test)
        com.HiProtobuf.HiProtobuf.Test_classname.Excel_TestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Excel_Test_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Excel_Test_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test.class, com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test.Builder.class);
      }

      // Construct using com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableData().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.HiProtobuf.HiProtobuf.Test_classname.internal_static_HiProtobuf_Excel_Test_descriptor;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test getDefaultInstanceForType() {
        return com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test.getDefaultInstance();
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test build() {
        com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test buildPartial() {
        com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test result = new com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test(this);
        int from_bitField0_ = bitField0_;
        result.data_ = internalGetData();
        result.data_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test) {
          return mergeFrom((com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test other) {
        if (other == com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test.getDefaultInstance()) return this;
        internalGetMutableData().mergeFrom(
            other.internalGetData());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test> data_;
      private com.google.protobuf.MapField<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test>
      internalGetData() {
        if (data_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              DataDefaultEntryHolder.defaultEntry);
        }
        return data_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test>
      internalGetMutableData() {
        onChanged();;
        if (data_ == null) {
          data_ = com.google.protobuf.MapField.newMapField(
              DataDefaultEntryHolder.defaultEntry);
        }
        if (!data_.isMutable()) {
          data_ = data_.copy();
        }
        return data_;
      }

      public int getDataCount() {
        return internalGetData().getMap().size();
      }
      /**
       * <code>map&lt;int32, .HiProtobuf.Test&gt; Data = 1;</code>
       */

      public boolean containsData(
          int key) {
        
        return internalGetData().getMap().containsKey(key);
      }
      /**
       * Use {@link #getDataMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test> getData() {
        return getDataMap();
      }
      /**
       * <code>map&lt;int32, .HiProtobuf.Test&gt; Data = 1;</code>
       */

      public java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test> getDataMap() {
        return internalGetData().getMap();
      }
      /**
       * <code>map&lt;int32, .HiProtobuf.Test&gt; Data = 1;</code>
       */

      public com.HiProtobuf.HiProtobuf.Test_classname.Test getDataOrDefault(
          int key,
          com.HiProtobuf.HiProtobuf.Test_classname.Test defaultValue) {
        
        java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test> map =
            internalGetData().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, .HiProtobuf.Test&gt; Data = 1;</code>
       */

      public com.HiProtobuf.HiProtobuf.Test_classname.Test getDataOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test> map =
            internalGetData().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearData() {
        internalGetMutableData().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, .HiProtobuf.Test&gt; Data = 1;</code>
       */

      public Builder removeData(
          int key) {
        
        internalGetMutableData().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test>
      getMutableData() {
        return internalGetMutableData().getMutableMap();
      }
      /**
       * <code>map&lt;int32, .HiProtobuf.Test&gt; Data = 1;</code>
       */
      public Builder putData(
          int key,
          com.HiProtobuf.HiProtobuf.Test_classname.Test value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableData().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, .HiProtobuf.Test&gt; Data = 1;</code>
       */

      public Builder putAllData(
          java.util.Map<java.lang.Integer, com.HiProtobuf.HiProtobuf.Test_classname.Test> values) {
        internalGetMutableData().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HiProtobuf.Excel_Test)
    }

    // @@protoc_insertion_point(class_scope:HiProtobuf.Excel_Test)
    private static final com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test();
    }

    public static com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Excel_Test>
        PARSER = new com.google.protobuf.AbstractParser<Excel_Test>() {
      @java.lang.Override
      public Excel_Test parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Excel_Test(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Excel_Test> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Excel_Test> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.HiProtobuf.HiProtobuf.Test_classname.Excel_Test getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HiProtobuf_Test_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HiProtobuf_Test_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HiProtobuf_Excel_Test_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HiProtobuf_Excel_Test_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HiProtobuf_Excel_Test_DataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HiProtobuf_Excel_Test_DataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTest.proto\022\nHiProtobuf\"K\n\004Test\022\n\n\002id\030\001" +
      " \001(\005\022\014\n\004name\030\002 \001(\t\022\n\n\002hp\030\003 \001(\005\022\016\n\006attack" +
      "\030\004 \001(\005\022\r\n\005infos\030\005 \003(\t\"{\n\nExcel_Test\022.\n\004D" +
      "ata\030\001 \003(\0132 .HiProtobuf.Excel_Test.DataEn" +
      "try\032=\n\tDataEntry\022\013\n\003key\030\001 \001(\005\022\037\n\005value\030\002" +
      " \001(\0132\020.HiProtobuf.Test:\0028\001B8\n\031com.HiProt" +
      "obuf.HiProtobufB\016Test_classname\252\002\nHiProt" +
      "obufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HiProtobuf_Test_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HiProtobuf_Test_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HiProtobuf_Test_descriptor,
        new java.lang.String[] { "Id", "Name", "Hp", "Attack", "Infos", });
    internal_static_HiProtobuf_Excel_Test_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HiProtobuf_Excel_Test_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HiProtobuf_Excel_Test_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_HiProtobuf_Excel_Test_DataEntry_descriptor =
      internal_static_HiProtobuf_Excel_Test_descriptor.getNestedTypes().get(0);
    internal_static_HiProtobuf_Excel_Test_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HiProtobuf_Excel_Test_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
