//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2022/9/8 10:30:29]

using System.Collections.Generic;

public class EnemyConfigItem
{
    public int id;
    public int maxHp;
    public int maxMp;
    public int physicAttack;
    public float moveSpeed;
    public float attackCooldown;
    public int exp;
    public string modelPath;
}

public class EnemyConfigTable : TableManager<EnemyConfigItem, EnemyConfigTable>
{
    public override bool Load()
    {
        TableReader tr = new TableReader();
        DataReader dr = new DataReader();
        MyDataTable dt = tr.ReadFile(new MyConfig().WorkDir+"EnemyConfig.txt");

        foreach(MyDataRow row in dt.Rows)
        {
            var item = new EnemyConfigItem();
             item.id = dr.GetInt(row["id"].ToString());
             item.maxHp = dr.GetInt(row["maxHp"].ToString());
             item.maxMp = dr.GetInt(row["maxMp"].ToString());
             item.physicAttack = dr.GetInt(row["physicAttack"].ToString());
             item.moveSpeed = dr.GetFloat(row["moveSpeed"].ToString());
             item.attackCooldown = dr.GetFloat(row["attackCooldown"].ToString());
             item.exp = dr.GetInt(row["exp"].ToString());
             item.modelPath = (row["modelPath"].ToString());
              m_Items[item.id] = item;
        }
        return true;
    }
}


public class HeroConfigItem
{
    public int id;
    public int maxHp;
    public int maxMp;
    public int physicAttack;
    public int magicAttack;
    public float moveSpeed;
    public string modelPath;
    public int defaultSkillId;
}

public class HeroConfigTable : TableManager<HeroConfigItem, HeroConfigTable>
{
    public override bool Load()
    {
        TableReader tr = new TableReader();
        DataReader dr = new DataReader();
        MyDataTable dt = tr.ReadFile(new MyConfig().WorkDir+"HeroConfig.txt");

        foreach(MyDataRow row in dt.Rows)
        {
            var item = new HeroConfigItem();
             item.id = dr.GetInt(row["id"].ToString());
             item.maxHp = dr.GetInt(row["maxHp"].ToString());
             item.maxMp = dr.GetInt(row["maxMp"].ToString());
             item.physicAttack = dr.GetInt(row["physicAttack"].ToString());
             item.magicAttack = dr.GetInt(row["magicAttack"].ToString());
             item.moveSpeed = dr.GetFloat(row["moveSpeed"].ToString());
             item.modelPath = (row["modelPath"].ToString());
             item.defaultSkillId = dr.GetInt(row["defaultSkillId"].ToString());
              m_Items[item.id] = item;
        }
        return true;
    }
}


public class HeroLevelItem
{
    public int id;
    public int exp;
}

public class HeroLevelTable : TableManager<HeroLevelItem, HeroLevelTable>
{
    public override bool Load()
    {
        TableReader tr = new TableReader();
        DataReader dr = new DataReader();
        MyDataTable dt = tr.ReadFile(new MyConfig().WorkDir+"HeroLevel.txt");

        foreach(MyDataRow row in dt.Rows)
        {
            var item = new HeroLevelItem();
             item.id = dr.GetInt(row["id"].ToString());
             item.exp = dr.GetInt(row["exp"].ToString());
              m_Items[item.id] = item;
        }
        return true;
    }
}


public class LevelConfigItem
{
    public int id;
    public int totalLevel;
    public int totalTime;
}

public class LevelConfigTable : TableManager<LevelConfigItem, LevelConfigTable>
{
    public override bool Load()
    {
        TableReader tr = new TableReader();
        DataReader dr = new DataReader();
        MyDataTable dt = tr.ReadFile(new MyConfig().WorkDir+"LevelConfig.txt");

        foreach(MyDataRow row in dt.Rows)
        {
            var item = new LevelConfigItem();
             item.id = dr.GetInt(row["id"].ToString());
             item.totalLevel = dr.GetInt(row["totalLevel"].ToString());
             item.totalTime = dr.GetInt(row["totalTime"].ToString());
              m_Items[item.id] = item;
        }
        return true;
    }
}


public class LevelDetailItem
{
    public int id;
    public int time;
    public int characterId;
    public int num;
}

public class LevelDetailTable : TableManager<LevelDetailItem, LevelDetailTable>
{
    public override bool Load()
    {
        TableReader tr = new TableReader();
        DataReader dr = new DataReader();
        MyDataTable dt = tr.ReadFile(new MyConfig().WorkDir+"LevelDetail.txt");

        foreach(MyDataRow row in dt.Rows)
        {
            var item = new LevelDetailItem();
             item.id = dr.GetInt(row["id"].ToString());
             item.time = dr.GetInt(row["time"].ToString());
             item.characterId = dr.GetInt(row["characterId"].ToString());
             item.num = dr.GetInt(row["num"].ToString());
              m_Items[item.id] = item;
        }
        return true;
    }
}


public class NPCPropertyItem
{
    public int id;
    public int maxHp;
    public int maxMp;
    public int physic;
    public int magic;
    public int attackRange;
    public int viewRange;
    public int moveSpeed;
    public int turnSpeed;
    public List<float> startPoint;
    public float maxRadius;
    public string modelPath;
    public List<int> skillList;
}

public class NPCPropertyTable : TableManager<NPCPropertyItem, NPCPropertyTable>
{
    public override bool Load()
    {
        TableReader tr = new TableReader();
        DataReader dr = new DataReader();
        MyDataTable dt = tr.ReadFile(new MyConfig().WorkDir+"NPCProperty.txt");

        foreach(MyDataRow row in dt.Rows)
        {
            var item = new NPCPropertyItem();
             item.id = dr.GetInt(row["id"].ToString());
             item.maxHp = dr.GetInt(row["maxHp"].ToString());
             item.maxMp = dr.GetInt(row["maxMp"].ToString());
             item.physic = dr.GetInt(row["physic"].ToString());
             item.magic = dr.GetInt(row["magic"].ToString());
             item.attackRange = dr.GetInt(row["attackRange"].ToString());
             item.viewRange = dr.GetInt(row["viewRange"].ToString());
             item.moveSpeed = dr.GetInt(row["moveSpeed"].ToString());
             item.turnSpeed = dr.GetInt(row["turnSpeed"].ToString());
             item.startPoint = dr.GetFloatList(row["startPoint"].ToString());
             item.maxRadius = dr.GetFloat(row["maxRadius"].ToString());
             item.modelPath = (row["modelPath"].ToString());
             item.skillList = dr.GetIntList(row["skillList"].ToString());
              m_Items[item.id] = item;
        }
        return true;
    }
}


public class skillItem
{
    public int id;
    public string config;
    public int priority;
    public string icon;
}

public class skillTable : TableManager<skillItem, skillTable>
{
    public override bool Load()
    {
        TableReader tr = new TableReader();
        DataReader dr = new DataReader();
        MyDataTable dt = tr.ReadFile(new MyConfig().WorkDir+"skill.txt");

        foreach(MyDataRow row in dt.Rows)
        {
            var item = new skillItem();
             item.id = dr.GetInt(row["id"].ToString());
             item.config = (row["config"].ToString());
             item.priority = dr.GetInt(row["priority"].ToString());
             item.icon = (row["icon"].ToString());
              m_Items[item.id] = item;
        }
        return true;
    }
}


public class SkillMapItem
{
    public int id;
    public string config;
    public string icon;
}

public class SkillMapTable : TableManager<SkillMapItem, SkillMapTable>
{
    public override bool Load()
    {
        TableReader tr = new TableReader();
        DataReader dr = new DataReader();
        MyDataTable dt = tr.ReadFile(new MyConfig().WorkDir+"SkillMap.txt");

        foreach(MyDataRow row in dt.Rows)
        {
            var item = new SkillMapItem();
             item.id = dr.GetInt(row["id"].ToString());
             item.config = (row["config"].ToString());
             item.icon = (row["icon"].ToString());
              m_Items[item.id] = item;
        }
        return true;
    }
}

public class TableConfig : SingletonTable<TableConfig>
{
    public bool LoadTableConfig()
    {
       if (!EnemyConfigTable.Instance.Load()) return false;
       if (!HeroConfigTable.Instance.Load()) return false;
       if (!HeroLevelTable.Instance.Load()) return false;
       if (!LevelConfigTable.Instance.Load()) return false;
       if (!LevelDetailTable.Instance.Load()) return false;
       if (!NPCPropertyTable.Instance.Load()) return false;
       if (!skillTable.Instance.Load()) return false;
       if (!SkillMapTable.Instance.Load()) return false;
        return true;
    }
}
