//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2020/3/8 15:14:51]
#pragma once
# include "tabletool/myconfig.h"
# include "tabletool/singleton.h"
# include "tabletool/readtablefield.h"
# include "tablestruct.h"


bool LoadTableConfig();


struct tbsAchiveItem {
  int id;
  int line;
  tbsIdCount test1;
  vector<int> test2;
  vector<tbsKeyValue> test3;
};

class cfgAchiveTable:public IConfigTable<tbsAchiveItem>{
public:
    virtual bool Load();

    string GetTableFile()
    {
        string f = WORK_DIR;
        f = f + "Achive.txt";
        return f;
    }

};


struct tbsAchive2Item {
  int id;
  int line;
};

class cfgAchive2Table:public IConfigTable<tbsAchive2Item>{
public:
    virtual bool Load();

    string GetTableFile()
    {
        string f = WORK_DIR;
        f = f + "Achive2.txt";
        return f;
    }

};

